export const PermissionName = new Map([
	// General Permission
	['Administrator', 'Administrator'],
	['ViewAuditLog', 'View Audit Log'],
	['ManageGuild', 'Manage Guild'],
	['ManageRoles', 'Manage Roles'],
	['ManageChannels', 'Manage Channels'],
	['KickMembers', 'Kick Members'],
	['BanMembers', 'Ban Members'],
	['CreateInstantInvite', 'Create Instant Invite'],
	['ChangeNickname', 'Change Nickname'],
	['ManageNicknames', 'Manage Nicknames'],
	['ManageEmojisAndStickers', 'Manage Emojis and Stickers'],
	['ManageWebhooks', 'Manage Webhooks'],
	['ViewChannel', 'View Channel'],
	['ManageEvents', 'Manage Events'],
	['ModerateMembers', 'Moderate Members'],
	// Text Permission
	['SendMessages', 'Send Messages'],
	['CreatePublicThreads', 'Create Public Threads'],
	['CreatePrivateThreads', 'Create Private Threads'],
	['SendMessagesInThreads', 'Send Messages in Threads'],
	['SendTTSMessages', 'Send TTS Messages'],
	['ManageMessages', 'Manage Messages'],
	['ManageThreads', 'Manage Threads'],
	['EmbedLinks', 'Embed Links'],
	['AttachFiles', 'Attach Files'],
	['ReadMessageHistory', 'Read Message History'],
	['MentionEveryone', 'Mention Everyone'],
	['UseExternalEmojis', 'Use External Emojis'],
	['UseExternalStickers', 'Use External Stickers'],
	['AddReactions', 'Add Reactions'],
	['UseApplicationCommands', 'Use Slash Commands'],
	['UseEmbeddedActivities', 'Use Embedded Activities'],
	// Voice Permission
	['Connect', 'Connect'],
	['Speak', 'Speak'],
	['MuteMembers', 'Mute Members'],
	['DeafenMembers', 'Deafen Members'],
	['MoveMembers', 'Move Members'],
	['UseVAD', 'Use VAD'],
	['PrioritySpeaker', 'Priority Speaker'],
	['Stream', 'Stream'],
])